agregar = '/html/body/app-root/app-main-page/app-cv-outlet/app-cv/div[2]/div[1]/div[1]/div[1]/div[2]/div/a'
puesto = '/html/body/app-root/app-main-page/app-cv-outlet/app-experience/div/div/div[1]/form/div[1]/input'
tipoPuesto = '/html/body/app-root/app-main-page/app-cv-outlet/app-experience/div/div/div[1]/form/div[2]/select'
empresa = '/html/body/app-root/app-main-page/app-cv-outlet/app-experience/div/div/div[1]/form/div[3]/input'
fecha = '/html/body/app-root/app-main-page/app-cv-outlet/app-experience/div/div/div[1]/form/div[4]/input'
si = '/html/body/app-root/app-main-page/app-cv-outlet/app-experience/div/div/div[1]/form/div[5]/div/div[1]/label'
no = '/html/body/app-root/app-main-page/app-cv-outlet/app-experience/div/div/div[1]/form/div[5]/div/div[2]/label'

genteSi = '/html/body/app-root/app-main-page/app-cv-outlet/app-experience/div/div/div[1]/form/div[6]/div/div[1]/label'
genteNo = '/html/body/app-root/app-main-page/app-cv-outlet/app-experience/div/div/div[1]/form/div[6]/div/div[2]/label'
humanos = '/html/body/app-root/app-main-page/app-cv-outlet/app-experience/div/div/div[1]/form/div[7]/input'
funciones = '/html/body/app-root/app-main-page/app-cv-outlet/app-experience/div/div/div[1]/form/div[8]/textarea'
cancelar = '/html/body/app-root/app-main-page/app-cv-outlet/app-experience/div/div/div[1]/form/div[9]/button[1]'
guardar = '/html/body/app-root/app-main-page/app-cv-outlet/app-experience/div/div/div[1]/form/div[9]/button[2]'
