crearCuenta = '/html/body/app-root/app/div/div[2]/form/div/div[4]/button[2]'
email = '/html/body/app-root/app/div/div[2]/form/div/div[4]/div/input'
siguiente = '/html/body/app-root/app/div/div[2]/form/div/div[5]/button'
tokens = '/html/body/app-root/app/div/div[1]/p'
cBoxlegal1 = '/html/body/app-root/app/div/div[2]/form/div/div[3]/div[1]/label'
cBoxlegal2 = '/html/body/app-root/app/div/div[2]/form/div/div[3]/div[2]/label'
legales1 = '/html/body/app-root/app/div/div[2]/form/div/div[3]/div[1]/label/a'
legales2 = '/html/body/app-root/app/div/div[2]/form/div/div[3]/div[2]/label/a'
