crearCuenta = '/html/body/app-root/app/div/div[2]/div/form/div[3]/button[2]'
email = '/html/body/app-root/app/div/div[2]/div/form/div[1]/div/input'
siguiente = '/html/body/app-root/app/div/div[2]/div/form/div[3]/button[1]'
tokens = '/html/body/app-root/app/div/div[1]/p'
cBoxlegal1 = '//*[@id="check1"]'
cBoxlegal2 = '//*[@id="check2"]'
legales1 = '/html/body/app-root/app/div/div[2]/div/form/div[2]/div[1]/label/a'
legales2 = '/html/body/app-root/app/div/div[2]/div/form/div[2]/div[2]/label/a'
