busqueda = '/html/body/app-root/app-main-page/app-header/div[1]/div[1]/div[2]/div[1]/a'
favoritos = '/html/body/app-root/app-main-page/app-header/div[1]/div[1]/div[2]/div[2]/a'
corazon1 = '/html/body/app-root/app-main-page/app-vacancies-outlet/div/div/app-search/div[2]/div/div[2]/div[1]/div[1]/button[2]/i'
corazon2 = '/html/body/app-root/app-main-page/app-vacancies-outlet/div/div/app-search/div[2]/div/div[3]/div[1]/div[1]/button[2]/i'
corazon3 = '/html/body/app-root/app-main-page/app-vacancies-outlet/div/div/app-search/div[2]/div/div[4]/div[1]/div[1]/button[2]/i'
corazon4 = '/html/body/app-root/app-main-page/app-vacancies-outlet/div/div/app-search/div[2]/div/div[5]/div[1]/div[1]/button[2]/i'

favorito1 = '/html/body/app-root/app-main-page/app-vacancies-outlet/div/div/app-favorites/div/div/div[1]/div/button/i'
favorito2 = '/html/body/app-root/app-main-page/app-vacancies-outlet/div/div/app-favorites/div/div/div[2]/div/button/i'
favorito3 = '/html/body/app-root/app-main-page/app-vacancies-outlet/div/div/app-favorites/div/div/div[3]/div/button/i'
favorito4 = '/html/body/app-root/app-main-page/app-vacancies-outlet/div/div/app-favorites/div/div/div[4]/div/button/i'