ajustes = '/html/body/app-root/app-main-page/app-header/div[1]/div[1]/div[3]/div/button[2]'
cuentaSeguridad = '//*[@id="headingOne"]/h2/button'
correo = '//*[@id="email-tab"]'
email = '//*[@id="email"]/app-change-email/div/div/div/form/div[1]/input'
passwordEmail = '//*[@id="email"]/app-change-email/div/div/div/form/div[2]/input'
mostrarEmail = '//*[@id="email"]/app-change-email/div/div/div/form/div[2]/span/small[1]'
ocultarEmail = '//*[@id="email"]/app-change-email/div/div/div/form/div[2]/span/small[2]'
siguienteEmail = '//*[@id="email"]/app-change-email/div/div/div/form/button'

telefono = '//*[@id="phone-tab"]'
phone = '//*[@id="phone"]/app-change-phone/div/div/div/form/div[1]/input'
passwordPhone = '//*[@id="phone"]/app-change-phone/div/div/div/form/div[2]/input'
mostrarPhone = '//*[@id="phone"]/app-change-phone/div/div/div/form/div[2]/span/small[1]'
ocultarPhone = '//*[@id="phone"]/app-change-phone/div/div/div/form/div[2]/span/small[2]'
siguientePhone = '//*[@id="phone"]/app-change-phone/div/div/div/form/button'
code = '//*[@id="phone"]/app-change-phone/div/div/div/p'
code1 = '//*[@id="phone"]/app-change-phone/div/div/div/form/div/div/span[1]/input'
code2 = '//*[@id="phone"]/app-change-phone/div/div/div/form/div/div/span[2]/input'
code3 = '//*[@id="phone"]/app-change-phone/div/div/div/form/div/div/span[3]/input'
code4 = '//*[@id="phone"]/app-change-phone/div/div/div/form/div/div/span[4]/input'
volveEnviar = '//*[@id="phone"]/app-change-phone/div/div/div/form/button[2]'
siguientePhone2 = '//*[@id="phone"]/app-change-phone/div/div/div/form/button[1]'

passw = '//*[@id="password-tab"]'
password = '//*[@id="password"]/app-change-password/form/div[1]/div[1]/input'
mostrar1 = '//*[@id="password"]/app-change-password/form/div[1]/div[1]/span/small[1]'
ocultar1= '//*[@id="password"]/app-change-password/form/div[1]/div[1]/span/small[2]'
passwordNew = '//*[@id="password"]/app-change-password/form/div[1]/div[2]/input'
mostrar2 = '//*[@id="password"]/app-change-password/form/div[1]/div[2]/span/small[1]'
ocultar2 = '//*[@id="password"]/app-change-password/form/div[1]/div[2]/span/small[2]'
passwordNew2 = '//*[@id="password"]/app-change-password/form/div[2]/div/input'
mostrar3 = '//*[@id="password"]/app-change-password/form/div[2]/div/span/small[1]'
ocultar3 = '//*[@id="password"]/app-change-password/form/div[2]/div/span/small[2]'
cambiar = '//*[@id="password"]/app-change-password/form/div[3]/button'

